#
# Copyright (C) 2023 LilyChou Development
#
# This  script is licensed under GNU General Public License 2.0 or higher
#
# Modified OpenWRT source code from Lienol
#   [https://github.com/lienol/openwrt]
#
name: Compile Lienol Openwrt Defaults

on:
  workflow_dispatch:

jobs:
  build:
    name: Lienol Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Environment
        run: |
          sudo apextract xz file command linet-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 curl gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf tree

      - name: Directory Debuging
        run: tree ~/
